import { AnnouncementCard, EventCard, FacilityCard, MediaCard } from '@/components/Cards';
import { Hero, QuickActions, SectionHeading } from '@/components/LayoutParts';
import { content } from '@/lib/content';
import { t, type Locale } from '@/i18n';

export default function LocaleHomePage({ params }: { params: { locale: Locale } }) {
  const locale = params.locale;
  return <><Hero locale={locale} /><section className="container-shell section-pad"><QuickActions locale={locale} /></section><section className="container-shell section-pad pt-0"><SectionHeading eyebrow={t[locale].labels.upcoming} title={locale === 'ar' ? 'التسجيلات والأنشطة القادمة' : 'Upcoming registrations and activities'} body={locale === 'ar' ? 'بطاقات واضحة للفعاليات، الروابط، المكان، الفئة، وسياسة المرافق عند توفرها.' : 'Clear cards for event status, registration links, location, category, and guest rules when available.'} /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{content.events.slice(0, 3).map((event) => <EventCard key={event.id} event={event} locale={locale} />)}</div></section><section className="bg-white"><div className="container-shell section-pad"><SectionHeading title={locale === 'ar' ? 'إدارة رياضية تخدم الحياة الجامعية' : 'A sports administration built around campus life'} body={locale === 'ar' ? 'تنظم الإدارة البرامج والبطولات، تدير جداول المرافق، وتدعم مشاركة الطلبة والموظفين في بيئة صحية ومنظمة.' : 'The administration organizes programs and tournaments, coordinates facility schedules, and supports student and employee participation in a healthy university environment.'} /><div className="grid gap-5 md:grid-cols-3">{content.facilities.slice(0, 3).map((facility) => <FacilityCard key={facility.id} facility={facility} locale={locale} />)}</div></div></section><section className="container-shell section-pad"><SectionHeading title={locale === 'ar' ? 'الأخبار والتنبيهات' : 'News and announcements'} /><div className="grid gap-5 md:grid-cols-3">{content.announcements.slice(0, 3).map((item) => <AnnouncementCard key={item.id} item={item} locale={locale} />)}</div></section><section className="bg-white"><div className="container-shell section-pad"><SectionHeading title={locale === 'ar' ? 'جريدة آفاق والأرشيف الرياضي' : 'Afaq newspaper and media archive'} /><div className="grid gap-5 md:grid-cols-3">{content.media.slice(0, 3).map((item) => <MediaCard key={item.id} item={item} locale={locale} />)}</div></div></section></>;
}
